version: "3"
services:
    server:
        build: Server/
        ports:
            - "3001:3000"
    client:
        build: client/
        volumes:
            - ./client/src:/app
        ports:
            - "4201:4200"

       