GET http://localhost:3000/usersAll HTTP/1.1

###

POST  http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "email": "test033000.baror12dsd@gmail.com",
  "name": "test0033000 moshe"
}

###

PATCH http://localhost:3000/users/5bca16559934b15a HTTP/1.1
content-type: application/json

{
  "firstName": "Yaacov",
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###

DELETE http://localhost:3000/users/13b473f8194fa012 HTTP/1.1

###