GET http://localhost:3000/usersAll HTTP/1.1

###

POST http://localhost:3000/usersEmail HTTP/1.1
content-type: application/json

{
  "email": "chbaror@gmail.com"
}
###


POST http://localhost:3000/usercheckCode HTTP/1.1
content-type: application/json

{
  "email": "chbaror@gmail.com",
  "code" : "4887"
}

###
POST  http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name": "admin1 test",
  "email": "chbaror@gmail.com",
  "PhoneNumber":"0527158877"
}

###

PATCH http://localhost:3000/users/5bca16559934b15a HTTP/1.1
content-type: application/json

{
  "firstName": "Yaacov",
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###

DELETE http://localhost:3000/users/4fcf73cc30b69e28 HTTP/1.1

###