GET http://localhost:3000/usersAll HTTP/1.1

###

POST http://localhost:3000/usersEmail HTTP/1.1
content-type: application/json

{
  "email": "chaim@agggdm8in.com"

}
###

POST  http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name": "admin1 test",
  "email": "admincha9im@admin.com",
  "PhoneNumber":"0527158770"
}

###

PATCH http://localhost:3000/users/5bca16559934b15a HTTP/1.1
content-type: application/json

{
  "firstName": "Yaacov",
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###

DELETE http://localhost:3000/users/4fcf73cc30b69e28 HTTP/1.1

###